In [1]:
#1
from urllib.request import urlopen
from bs4 import BeautifulSoup
html = urlopen('https://en.wikipedia.org/wiki/Main_Page')
bs = BeautifulSoup(html, "html.parser")
titles = bs.find_all(['h1', 'h2','h3','h4','h5','h6'])
print('List all the header tags :', *titles, sep='\n\n')

List all the header tags :

<h1 class="firstHeading mw-first-heading" id="firstHeading" style="display: none"><span class="mw-page-title-main">Main Page</span></h1>

<h1><span class="mw-headline" id="Welcome_to_Wikipedia">Welcome to <a href="/wiki/Wikipedia" title="Wikipedia">Wikipedia</a></span></h1>

<h2 class="mp-h2" id="mp-tfa-h2"><span id="From_today.27s_featured_article"></span><span class="mw-headline" id="From_today's_featured_article">From today's featured article</span></h2>

<h2 class="mp-h2" id="mp-dyk-h2"><span class="mw-headline" id="Did_you_know_...">Did you know ...</span></h2>

<h2 class="mp-h2" id="mp-itn-h2"><span class="mw-headline" id="In_the_news">In the news</span></h2>

<h2 class="mp-h2" id="mp-otd-h2"><span class="mw-headline" id="On_this_day">On this day</span></h2>

<h2 class="mp-h2" id="mp-tfl-h2"><span id="From_today.27s_featured_list"></span><span class="mw-headline" id="From_today's_featured_list">From today's featured list</span></h2>

<h2 class="mp-h2" id="mp-tfp-h2"><span id="Today.27s_featured_picture"></span><span class="mw-headline" id="Today's_featured_picture">Today's featured picture</span></h2>

<h2 class="mp-h2" id="mp-other"><span class="mw-headline" id="Other_areas_of_Wikipedia">Other areas of Wikipedia</span></h2>

<h2 class="mp-h2" id="mp-sister"><span id="Wikipedia.27s_sister_projects"></span><span class="mw-headline" id="Wikipedia's_sister_projects">Wikipedia's sister projects</span></h2>

<h2 class="mp-h2" id="mp-lang"><span class="mw-headline" id="Wikipedia_languages">Wikipedia languages</span></h2>

<h2>Navigation menu</h2>

<h3 class="vector-menu-heading" id="p-personal-label">
<span class="vector-menu-heading-label">Personal tools</span>
</h3>

<h3 class="vector-menu-heading" id="p-namespaces-label">
<span class="vector-menu-heading-label">Namespaces</span>
</h3>

<h3 class="vector-menu-heading" id="p-views-label">
<span class="vector-menu-heading-label">Views</span>
</h3>

<h3>
<label for="searchInput">Search</label>
</h3>

<h3 class="vector-menu-heading" id="p-navigation-label">
<span class="vector-menu-heading-label">Navigation</span>
</h3>

<h3 class="vector-menu-heading" id="p-interaction-label">
<span class="vector-menu-heading-label">Contribute</span>
</h3>

<h3 class="vector-menu-heading" id="p-tb-label">
<span class="vector-menu-heading-label">Tools</span>
</h3>

<h3 class="vector-menu-heading" id="p-coll-print_export-label">
<span class="vector-menu-heading-label">Print/export</span>
</h3>

<h3 class="vector-menu-heading" id="p-wikibase-otherprojects-label">
<span class="vector-menu-heading-label">In other projects</span>
</h3>

<h3 class="vector-menu-heading" id="p-lang-label">
<span class="vector-menu-heading-label">Languages</span>
</h3>

In [3]:
#2
from bs4 import BeautifulSoup
import requests
import re
import pandas as pd

url = 'https://www.imdb.com/chart/top'
response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")
movies = soup.select('td.titleColumn')
crew = [a.attrs.get('title') for a in soup.select('td.titleColumn a')]
ratings = [b.attrs.get('data-value')
        for b in soup.select('td.posterColumn span[name=ir]')]
 

list = []
 
for index in range(0, len(movies)):

    movie_string = movies[index].get_text()
    movie = (' '.join(movie_string.split()).replace('.', ''))
    movie_title = movie[len(str(index))+1:-7]
    year = re.search('\((.*?)\)', movie_string).group(1)
    data = {"movie_title": movie_title,
            "rating": ratings[index],
            "year": year,}
    list.append(data)

for movie in list:
    print(movie['movie_title'], '('+movie['year'] +
        ') -', movie['rating'])
 
 
df = pd.DataFrame(list)
df.to_csv('imdb_top_100_movies.csv',index=False)

The Shawshank Redemption (1994) - 9.234879040527098
The Godfather (1972) - 9.156465346982442
The Dark Knight (2008) - 8.988201851769979
The Godfather Part II (1974) - 8.984392999426017
12 Angry Men (1957) - 8.949849216644983
Schindler's List (1993) - 8.9369531576744
The Lord of the Rings: The Return of the King (2003) - 8.925768672081237
Pulp Fiction (1994) - 8.849141676749477
The Lord of the Rings: The Fellowship of the Ring (2001) - 8.806492663716734
 Il buono, il brutto, il cattivo (1966) - 8.79205092650221
Forrest Gump (1994) - 8.767881534900168
Fight Club (1999) - 8.748944048298315
Inception (2010) - 8.733237545825324
The Lord of the Rings: The Two Towers (2002) - 8.731489917663955
The Empire Strikes Back (1980) - 8.70070818726704
The Matrix (1999) - 8.670201221901118
Goodfellas (1990) - 8.652331719578964
One Flew Over the Cuckoo's Nest (1975) - 8.640047360060684
Se7en (1995) - 8.604302874134904
Shichinin no samurai (1954) - 8.598982575316153
It's a Wonderful Life (1946) - 8.596483165844587
The Silence of the Lambs (1991) - 8.58824757388551
Cidade de Deus (2002) - 8.57930461747469
Saving Private Ryan (1998) - 8.578766536587127
La vita è bella (1997) - 8.566703963061547
The Green Mile (1999) - 8.561381019986795
Interstellar (2014) - 8.561295133437893
Star Wars (1977) - 8.552107008616096
Terminator 2: Judgment Day (1991) - 8.536298477410794
Back to the Future (1985) - 8.517887040366913
Sen to Chihiro no kamikakushi (2001) - 8.515538789385392
Psycho (1960) - 8.508062270211182
The Pianist (2002) - 8.505819971622733
Léon (1994) - 8.497824614381335
Gisaengchung (2019) - 8.497037002521273
The Lion King (1994) - 8.488467265887781
Gladiator (2000) - 8.486391251803596
American History X (1998) - 8.483495707883327
The Departed (2006) - 8.475632468010453
The Usual Suspects (1995) - 8.474071622017831
The Prestige (2006) - 8.468586675226781
Casablanca (1942) - 8.463987887790632
Whiplash (2014) - 8.46324627260019
The Intouchables (2011) - 8.453793999265132
Hotaru no haka (1988) - 8.451309421139877
Seppuku (1962) - 8.450861576445504
Modern Times (1936) - 8.448583162959737
Once Upon a Time in the West (1968) - 8.445837941491261
Rear Window (1954) - 8.437064002698325
Alien (1979) - 8.434404908458276
City Lights (1931) - 8.434153489749983
Nuovo Cinema Paradiso (1988) - 8.431429486084612
Apocalypse Now (1979) - 8.424519183872087
Memento (2000) - 8.423671122460291
Raiders of the Lost Ark (1981) - 8.410013494348219
Django Unchained (2012) - 8.404951144280245
WALL·E (2008) - 8.39376569473199
The Lives of Others (2006) - 8.385477358408925
Sunset Blvd (1950) - 8.382780448434724
Paths of Glory (1957) - 8.371762699818982
The Shining (1980) - 8.366688772437202
The Great Dictator (1940) - 8.365847518565408
Avengers: Infinity War (2018) - 8.359471604739904
Witness for the Prosecution (1957) - 8.359366966768683
Aliens (1986) - 8.343804608309325
American Beauty (1999) - 8.33516042874748
Spider-Man: Into the Spider-Verse (2018) - 8.332307056054187
Dr Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1964) - 8.33154565092137
Top Gun: Maverick (2022) - 8.329364323505215
The Dark Knight Rises (2012) - 8.32810608865054
Oldeuboi (2003) - 8.320120097970895
Joker (2019) - 8.317257846159238
Amadeus (1984) - 8.31575481547074
Braveheart (1995) - 8.314978535518797
Toy Story (1995) - 8.314836184157075
Coco (2017) - 8.313622507501693
Inglourious Basterds (2009) - 8.313530431333993
Das Boot (1981) - 8.3122956178031
Avengers: Endgame (2019) - 8.303810045562983
Mononoke-hime (1997) - 8.30345197456327
Once Upon a Time in America (1984) - 8.2978238674305
Good Will Hunting (1997) - 8.28857579759897
Kimi no na wa (2016) - 8.27818438864911
Requiem for a Dream (2000) - 8.275536379386093
Toy Story 3 (2010) - 8.275050671001695
Singin' in the Rain (1952) - 8.273394661249483
3 Idiots (2009) - 8.272588282696042
Tengoku to jigoku (1963) - 8.267209300015818
Star Wars: Episode VI - Return of the Jedi (1983) - 8.266498720617692
2001: A Space Odyssey (1968) - 8.263583999829516
Eternal Sunshine of the Spotless Mind (2004) - 8.263176031537723
Reservoir Dogs (1992) - 8.262554249994663
Capharnaüm (2018) - 8.260630651823535
Jagten (2012) - 8.255754548054568
Lawrence of Arabia (1962) - 8.255072028078562
Citizen Kane (1941) - 8.254881457175907
M - Eine Stadt sucht einen Mörder (1931) - 8.254084168952511
North by Northwest (1959) - 8.251111979520697
Idi i smotri (1985) - 8.249158953894309
 Vertigo (1958) - 8.246193514186288
Le fabuleux destin d'Amélie Poulain (2001) - 8.24408032930346
A Clockwork Orange (1971) - 8.242341443917665
Double Indemnity (1944) - 8.23931852018434
The Apartment (1960) - 8.239110086863683
Full Metal Jacket (1987) - 8.23886449149892
Ikiru (1952) - 8.236029962350294
Scarface (1983) - 8.23541635048611
To Kill a Mockingbird (1962) - 8.228100329005564
The Sting (1973) - 8.228024154130692
Hamilton (2020) - 8.225914567697766
Heat (1995) - 8.224844902746547
Up (2009) - 8.224709825628901
Taxi Driver (1976) - 8.224689714195087
Incendies (2010) - 8.22243793444608
LA Confidential (1997) - 8.222275847370357
Jodaeiye Nader az Simin (2011) - 8.221539643329233
Metropolis (1927) - 8.220937505970005
Die Hard (1988) - 8.219285572910994
Snatch (2000) - 8.219194956287112
Ladri di biciclette (1948) - 8.218141116319929
Indiana Jones and the Last Crusade (1989) - 8.217709903553704
1917 (2019) - 8.21171263631774
Taare Zameen Par (2007) - 8.210425664508278
Der Untergang (2004) - 8.20414848514986
Per qualche dollaro in più (1965) - 8.201932353805551
Batman Begins (2005) - 8.200770604291785
Dangal (2016) - 8.200045101139553
The Kid (1921) - 8.193651324267723
Some Like It Hot (1959) - 8.19210170398238
All About Eve (1950) - 8.18134377203226
The Father (2020) - 8.180684477013143
Green Book (2018) - 8.175747388966718
The Wolf of Wall Street (2013) - 8.174014685630812
Judgment at Nuremberg (1961) - 8.170452543314791
Ran (1985) - 8.165719597967886
Casino (1995) - 8.16404361183985
Unforgiven (1992) - 8.162641856397105
Spider-Man: No Way Home (2021) - 8.162329012026468
Pan's Labyrinth (2006) - 8.162309299022068
There Will Be Blood (2007) - 8.157270009649494
The Truman Show (1998) - 8.155046734490314
The Sixth Sense (1999) - 8.153764368620925
A Beautiful Mind (2001) - 8.15236191361514
Monty Python and the Holy Grail (1975) - 8.14978595504796
Yôjinbô (1961) - 8.149716726216653
The Treasure of the Sierra Madre (1948) - 8.148537083056947
Shutter Island (2010) - 8.146834214283114
Jurassic Park (1993) - 8.145577964685552
Rashômon (1950) - 8.142332160535481
The Great Escape (1963) - 8.142136308950876
Kill Bill: Vol 1 (2003) - 8.137858453943243
No Country for Old Men (2007) - 8.137066248817444
Finding Nemo (2003) - 8.131717209870414
The Elephant Man (1980) - 8.129824924271587
Chinatown (1974) - 8.129144510588912
Raging Bull (1980) - 8.127900341676655
The Thing (1982) - 8.127563403991267
Gone with the Wind (1939) - 8.124978149655448
V for Vendetta (2005) - 8.12483053104121
Inside Out (2015) - 8.123240309822794
Lock, Stock and Two Smoking Barrels (1998) - 8.122008611703537
Dial M for Murder (1954) - 8.120404993825224
El secreto de sus ojos (2009) - 8.117381239266956
Hauru no ugoku shiro (2004) - 8.115290540936565
The Bridge on the River Kwai (1957) - 8.1132242087515
Three Billboards Outside Ebbing, Missouri (2017) - 8.111471944574012
Trainspotting (1996) - 8.110602401964318
Warrior (2011) - 8.104085058234302
Gran Torino (2008) - 8.103787151060315
Fargo (1996) - 8.102969039648151
Prisoners (2013) - 8.099430430531035
Tonari no Totoro (1988) - 8.09391387401167
Million Dollar Baby (2004) - 8.089544785358912
Catch Me If You Can (2002) - 8.088468118767578
The Gold Rush (1925) - 8.08683981849872
Blade Runner (1982) - 8.084922565297775
Bacheha-Ye aseman (1997) - 8.084184265849826
On the Waterfront (1954) - 8.083371987100074
The Third Man (1949) - 8.080809233536998
Before Sunrise (1995) - 8.079223349572768
12 Years a Slave (2013) - 8.079079452040519
Ben-Hur (1959) - 8.078624026348429
Smultronstället (1957) - 8.078129110461456
Harry Potter and the Deathly Hallows: Part 2 (2011) - 8.077946237763246
Gone Girl (2014) - 8.07727435277513
The General (1926) - 8.07688595959761
The Deer Hunter (1978) - 8.075032894969281
In the Name of the Father (1993) - 8.073992286110732
The Grand Budapest Hotel (2014) - 8.073863247866948
Barry Lyndon (1975) - 8.071580205554977
Le salaire de la peur (1953) - 8.071519520018771
Mr Smith Goes to Washington (1939) - 8.070010061406979
Sherlock Jr (1924) - 8.06917353169797
Hacksaw Ridge (2016) - 8.069119502608174
Salinui chueok (2003) - 8.068662864128994
Klaus (2019) - 8.067997204837877
Relatos salvajes (2014) - 8.06621757227691
Det sjunde inseglet (1957) - 8.065329572590567
Room (2015) - 8.06489949499149
Mad Max: Fury Road (2015) - 8.063041925296721
How to Train Your Dragon (2010) - 8.061886216732926
Mary and Max (2009) - 8.060974624032813
The Big Lebowski (1998) - 8.060826361363272
Jaws (1975) - 8.060478313015414
Monsters, Inc (2001) - 8.059686912257227
Everything Everywhere All at Once (2022) - 8.056483461524818
Tôkyô monogatari (1953) - 8.056340842253965
Dead Poets Society (1989) - 8.05487146157071
La passion de Jeanne d'Arc (1928) - 8.053961735974488
Hotel Rwanda (2004) - 8.051959858781338
Ford v Ferrari (2019) - 8.047341004657033
Rocky (1976) - 8.047308395127558
Platoon (1986) - 8.046271567691138
Pather Panchali (1955) - 8.041901209950929
The Terminator (1984) - 8.040943199745486
Stand by Me (1986) - 8.040937292194661
Spotlight (2015) - 8.040023946278957
Rush (2013) - 8.037942763306551
Logan (2017) - 8.037618060068874
Ratatouille (2007) - 8.03656303971334
Network (1976) - 8.03643631812094
Into the Wild (2007) - 8.03497382114295
The Wizard of Oz (1939) - 8.033872549098799
Groundhog Day (1993) - 8.030746797905554
Before Sunset (2004) - 8.030022759118486
Jai Bhim (2021) - 8.028784497299318
The Exorcist (1973) - 8.027394200568743
The Best Years of Our Lives (1946) - 8.026343221346158
The Incredibles (2004) - 8.02578062104196
To Be or Not to Be (1942) - 8.023892505842806
La battaglia di Algeri (1966) - 8.023146659058783
The Grapes of Wrath (1940) - 8.022644345417435
Rebecca (1940) - 8.021901470918797
Hachi: A Dog's Tale (2009) - 8.021778532317187
Pirates of the Caribbean: The Curse of the Black Pearl (2003) - 8.021130742390024
Cool Hand Luke (1967) - 8.021104318773235
Amores perros (2000) - 8.020888204956117
La haine (1995) - 8.01909695157613
Babam ve Oglum (2005) - 8.01762116212342
Les quatre cents coups (1959) - 8.015722428969058
Persona (1966) - 8.015042288518883
It Happened One Night (1934) - 8.01421158232723
The Sound of Music (1965) - 8.012687399266857
Life of Brian (1979) - 8.012525896958707
Ah-ga-ssi (2016) - 8.012423127299465
Dersu Uzala (1975) - 8.009032278708302
Aladdin (1992) - 8.005770011455619
Gandhi (1982) - 8.005728143751485
The Help (2011) - 8.005123639210966
The Iron Giant (1999) - 8.003049991975518

In [5]:
#3
from bs4 import BeautifulSoup
import requests
import re
import pandas as pd
 
url = 'https://www.imdb.com/india/top-rated-indian-movies/'
response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")
movies = soup.select('td.titleColumn')
ratings = [b.attrs.get('data-value')
        for b in soup.select('td.posterColumn span[name=ir]')]
 
list = []

for index in range(0, len(movies)):

    movie_string = movies[index].get_text()
    movie = (' '.join(movie_string.split()).replace('.', ''))
    movie_title = movie[len(str(index))+1:-7]
    year = re.search('\((.*?)\)', movie_string).group(1)
    place = movie[:len(str(index))-(len(movie))]
    data = {"movie_title": movie_title,
            "rating": ratings[index],
            "year": year}
    
    list.append(data)
for movie in list:
    print( movie['movie_title'], '('+movie['year'] +
        ') -', movie['rating'])

df = pd.DataFrame(list)
df.to_csv('imdb_top_100_Indian_movies.csv',index=False)

Rocketry: The Nambi Effect (2022) - 8.533315029744596
Anbe Sivam (2003) - 8.405154944408105
Jai Bhim (2021) - 8.39796684515959
Nayakan (1987) - 8.39696402675371
Golmaal (1979) - 8.395836236994601
777 Charlie (2022) - 8.38001938604429
Pariyerum Perumal (2018) - 8.3789960135749
3 Idiots (2009) - 8.35230106213353
Apur Sansar (1959) - 8.350484897741545
 Manichitrathazhu (1993) - 8.34727569689927
Kumbalangi Nights (2019) - 8.321047802173313
Black Friday (2004) - 8.31850834480106
Soorarai Pottru (2020) - 8.317474225906821
#Home (2021) - 8.315477593102667
C/o Kancharapalem (2018) - 8.313630155189616
Taare Zameen Par (2007) - 8.3007309226795
Kireedam (1989) - 8.29469754212759
Dangal (2016) - 8.283026836908723
Kaithi (2019) - 8.281987913700021
Jersey (2019) - 8.278753480588257
96 (2018) - 8.253634024356918
Maya Bazaar (1957) - 8.253528646253747
Asuran (2019) - 8.24885375378954
Thevar Magan (1992) - 8.245135539573834
Visaaranai (2015) - 8.237980654298868
Sarpatta Parambarai (2021) - 8.23381075093536
Natsamrat (2016) - 8.232417326174714
Drishyam 2 (2021) - 8.225524351082768
Thalapathi (1991) - 8.225126922542938
Pather Panchali (1955) - 8.219334929403026
Nadodikkattu (1987) - 8.196747910566003
Sardar Udham (2021) - 8.192995479636531
Thani Oruvan (2015) - 8.188898009247655
Vada Chennai (2018) - 8.183015227948669
Jaane Bhi Do Yaaro (1983) - 8.180505039852306
Sita Ramam (2022) - 8.178554019261549
Aparajito (1956) - 8.175546991599283
Khosla Ka Ghosla! (2006) - 8.169832224770676
Drishyam (2013) - 8.16265914679236
Peranbu (2018) - 8.153150558401885
Ratsasan (2018) - 8.150286141069381
Anniyan (2005) - 8.14934970845454
Chupke Chupke (1975) - 8.145824023574752
Mahanati (2018) - 8.143583006130873
Agent Sai Srinivasa Athreya (2019) - 8.141471895703011
Premam (2015) - 8.130175915145104
Bangalore Days (2014) - 8.129728391547479
Vikram (2022) - 8.129414125717915
Satya (1998) - 8.129069107808693
Super Deluxe (2019) - 8.126964954939666
Devasuram (1993) - 8.123880645992374
Gangs of Wasseypur (2012) - 8.1212706533823
Bhaag Milkha Bhaag (2013) - 8.109467509388764
Drishyam (2015) - 8.108818833506884
Aruvi (2016) - 8.107624500747397
Andhadhun (2018) - 8.106808881719422
Vikram Vedha (2017) - 8.106718400477552
Chithram (1988) - 8.104171770705344
Kannathil Muthamittal (2002) - 8.10392585190849
Guide (1965) - 8.10240201845878
Tumbbad (2018) - 8.096088766232134
Iruvar (1997) - 8.095961754958495
Sairat (2016) - 8.094523121198591
Shahid (2012) - 8.092487937301707
Zindagi Na Milegi Dobara (2011) - 8.091087102072759
Paan Singh Tomar (2012) - 8.087635250107947
Chhichhore (2019) - 8.084253736779903
Mudhalvan (1999) - 8.080140845394956
Spadikam (1995) - 8.074508059587986
Pudhu Pettai (2006) - 8.07157165368648
Dhuruvangal Pathinaaru (2016) - 8.070267751123135
Swades: We, the People (2004) - 8.070089896686333
Chak De! India (2007) - 8.068444288815762
Uri: The Surgical Strike (2019) - 8.068316594626019
Papanasam (2015) - 8.067172384575871
Black (2005) - 8.065904102694686
Mandela (2021) - 8.065892047873827
Jo Jeeta Wohi Sikandar (1992) - 8.064078321497291
Pyaasa (1957) - 8.063118604034619
Munna Bhai MBBS (2003) - 8.060636887638603
Soodhu Kavvum (2013) - 8.055160314239268
Article 15 (2019) - 8.05480672723594
Queen (2013) - 8.050107405873153
Kaakkaa Muttai (2014) - 8.049405585768964
Talvar (2015) - 8.048177932383014
Lagaan: Once Upon a Time in India (2001) - 8.048177074769804
PK (2014) - 8.043989532038784
Jigarthanda (2014) - 8.043543394047031
OMG: Oh My God! (2012) - 8.042438708439937
Hera Pheri (2000) - 8.03996735416619
Sarfarosh (1999) - 8.038011430010265
Theeran Adhigaaram Ondru (2017) - 8.034514920280932
Udaan (2010) - 8.034284683369025
Barfi! (2012) - 8.033289281001782
Sholay (1975) - 8.032858482394232
Ustad Hotel (2012) - 8.031701488738422
The Legend of Bhagat Singh (2002) - 8.028549245205719
Virumandi (2004) - 8.024326934507176
Baahubali 2: The Conclusion (2017) - 8.02243053552051
 Angoor (1982) - 8.020067085303358
Rang De Basanti (2006) - 8.0167114243775
Jana Gana Mana (2022) - 8.016539574469842
Baasha (1995) - 8.01587069702733
Maheshinte Prathikaaram (2016) - 8.013620009082308
Masaan (2015) - 8.010831909852053
Shershaah (2021) - 8.009728977738048
Kahaani (2012) - 8.00971076588439
Dil Chahta Hai (2001) - 8.007266233525991
A Wednesday (2008) - 8.005842269897913
Kaun Pravin Tambe? (2022) - 8.005620299570507
Roja (1992) - 8.001583321594664
Pithamagan (2003) - 8.001569304968191
Iqbal (2005) - 7.999228860098548
Pink (2016) - 7.996840902783709
Lage Raho Munna Bhai (2006) - 7.996529861520695
Nil Battey Sannata (2015) - 7.994401287407886
Anand (1971) - 7.985732736576353
Lucia (2013) - 7.979991937172344
Charulata (1964) - 7.979534303226406
Alai Payuthey (2000) - 7.978426903453158
Section 375 (2019) - 7.9765708593556965
Oru Vadakkan Veeragatha (1989) - 7.973007838992215
Omkara (2006) - 7.971524613892559
Bajrangi Bhaijaan (2015) - 7.970073897251337
Bommarillu (2006) - 7.964447823989519
Bombay (1995) - 7.963686611179959
KGF: Chapter 1 (2018) - 7.963189341222603
Indian (1996) - 7.955623925945112
KGF: Chapter 2 (2022) - 7.95438108102767
The Great Indian Kitchen (2021) - 7.952883509961415
Rangasthalam (2018) - 7.952872018341964
Haider (2014) - 7.939625480173589
Mughal-E-Azam (1960) - 7.93816038451701
Dilwale Dulhania Le Jayenge (1995) - 7.937181884079324
Maanaadu (2021) - 7.933243283356665
Athadu (2005) - 7.931801863976855
Maqbool (2003) - 7.9252049997402585
Thadam (2019) - 7.924339038370707
Andaz Apna Apna (1994) - 7.923698488249804
Special Chabbis (2013) - 7.923537609415801
Vaaranam Aayiram (2008) - 7.919588634838292
Android Kunjappan Version 525 (2019) - 7.91649010923239
Padayappa (1999) - 7.913965972059074
Pelli Choopulu (2016) - 7.911954006068186
Gulaal (2009) - 7.9101138503662405
Ulidavaru Kandanthe (2014) - 7.895685627859473
Naduvula Konjam Pakkatha Kaanom (2012) - 7.885257400681149
Deewaar (1975) - 7.883559207165853
Badhaai ho (2018) - 7.881127820597425
Ugly (2013) - 7.881108552409036
Evaru (2019) - 7.8809591339046445
Kshanam (2016) - 7.8808952514295685
Vaastav: The Reality (1999) - 7.880211055944048
Company (2002) - 7.879677037306539
Major (2022) - 7.8780745030569586
Gully Boy (2019) - 7.876997402359566
Aadukalam (2011) - 7.872549678466603
Padosan (1968) - 7.872476280870584
Maanagaram (2017) - 7.870524692976476
Nayattu (2021) - 7.867285861280763
Thondimuthalum Dhriksakshiyum (2017) - 7.859948266880852
DevD (2009) - 7.856190442171289
My Name Is Khan (2010) - 7.853120231473965
Take Off (2017) - 7.84859190072543
Pranchiyettan and the Saint (2010) - 7.848102254037573
Baishe Srabon (2011) - 7.843290999834211
Kal Ho Naa Ho (2003) - 7.839804631807882
Ayyappanum Koshiyum (2020) - 7.837724998654859
Dil Bechara (2020) - 7.835199226142897
Jab We Met (2007) - 7.832881919782452
Manjhi: The Mountain Man (2015) - 7.8318759581154955
Mukkabaaz (2017) - 7.830254151629757
Super 30 (2019) - 7.82767422085642
Karnan (2021) - 7.827154853724552
Arjun Reddy (2017) - 7.8267608082230415
Deiva Thirumagal (2011) - 7.82515949583913
Border (1997) - 7.8239485723799955
Ship of Theseus (2012) - 7.823682078999827
Charlie (2015) - 7.821386370231314
Vedam (2010) - 7.81836718783439
Bãhubali: The Beginning (2015) - 7.8127593399947495
Padman (2018) - 7.808169020752185
Salaam Bombay! (1988) - 7.807804172877036
Ankhon Dekhi (2013) - 7.80013586740025
RRR (Rise Roar Revolt) (Rise Roar Revolt) - 7.79685415208207
MS Dhoni: The Untold Story (2016) - 7.7965015031272715
Baby (2015) - 7.796356072819275
Jalsaghar (1958) - 7.796292105285275
Vinnaithaandi Varuvaayaa (2010) - 7.7954552857461845
Malik (2021) - 7.794978820363661
Pizza (2012) - 7.7899062845861895
Kirik Party (2016) - 7.788935536986488
The Tashkent Files (2019) - 7.784476944065325
Hridayam (2022) - 7.77873445414816
Memories (2013) - 7.776801003289229
Hindi Medium (2017) - 7.776768610763375
Lakshya (2004) - 7.774428252828546
English Vinglish (2012) - 7.773986848145437
Dor (2006) - 7.772664889050651
Airlift (2016) - 7.771746085397364
Joseph (2018) - 7.770828011729038
Hey Ram (2000) - 7.77067479746889
Johnny Gaddaar (2007) - 7.770494741813325
KaakhaKaakha: The Police (2003) - 7.766607802635531
Anjaam Pathiraa (2020) - 7.754718720711608
Gangaajal (2003) - 7.750860338921924
Vettaiyaadu Vilaiyaadu (2006) - 7.745335238975408
Okkadu (2003) - 7.738380498306306
Mumbai Police (2013) - 7.7354475604233635
Pokiri (2006) - 7.732539569753915
The Lunchbox (2013) - 7.7321497090323446
Ab Tak Chhappan (2004) - 7.729008737537196
Thuppakki (2012) - 7.726701296253039
Oopiri (2016) - 7.724333469754261
Unnaipol Oruvan (2009) - 7.721790450027969
Angamaly Diaries (2017) - 7.721462780275045
Manam (2014) - 7.7202905443349295
Karthikeya 2 (2022) - 7.719019368670695
RangiTaranga (2015) - 7.718895460677735
Ghilli (2004) - 7.715164506628597
Vicky Donor (2012) - 7.708024015085533
Secret Superstar (2017) - 7.705537875972722
Mother India (1957) - 7.70403184045514
Veer-Zaara (2004) - 7.70342813848872
Kaththi (2014) - 7.703315824054706
Mimi (2021) - 7.7022942928983005
Sonchiriya (2019) - 7.701351012968419
Dia (2020) - 7.6967729145314845
Rock On!! (2008) - 7.696082167995552
Stanley Ka Dabba (2011) - 7.696056862643401
Mr India (1987) - 7.695670208459277
Oru CBI Diary Kurippu (1988) - 7.695632143957907
Nayak: The Real Hero (2001) - 7.694731619123964
Thulladha Manamum Thullum (1999) - 7.694077878407196
Happy Days (2007) - 7.693942913291682
Udta Punjab (2016) - 7.693784014102828
Minnal Murali (2021) - 7.691857321273504
Aayirathil Oruvan (2010) - 7.689844151289339
Badla (2019) - 7.688689746337083
Raazi (2018) - 7.685069385541254
Dasvidaniya (2008) - 7.6830441484612315
Poove Unakkaga (1996) - 7.677203860528502
Kai po che! (2013) - 7.677129316438051
Goodachari (2018) - 7.672598424291904
Joji (2021) - 7.669362541140784
Thiruchitrambalam (2022) - 7.66127312653968
Ko (2011) - 7.654642222585844
Don (1978) - 7.653067091832536
Colour Photo (2020) - 7.649241231933117
Ennu Ninte Moideen (2015) - 7.648844827189723

In [6]:
#4
from bs4 import BeautifulSoup
import requests
import pandas as pd

url = "https://presidentofindia.nic.in/former-presidents.htm"

page = requests.get(url)
bs = BeautifulSoup(page.content, "html.parser")
nameList = bs.findAll(["h3"])
termofoffice = bs.findAll('span', class_="terms")
for name in nameList:
    print(name.get_text())

Shri Ram Nath Kovind (birth - 1945)
Shri Pranab Mukherjee (1935-2020)
Smt Pratibha Devisingh Patil (birth - 1934)
DR. A.P.J. Abdul Kalam (1931-2015)
Shri K. R. Narayanan (1920 - 2005)
Dr Shankar Dayal Sharma (1918-1999)
Shri R Venkataraman (1910-2009)
Giani Zail Singh (1916-1994)
Shri Neelam Sanjiva Reddy (1913-1996)
Dr. Fakhruddin Ali Ahmed (1905-1977)
Shri Varahagiri Venkata Giri (1894-1980)
Dr. Zakir Husain (1897-1969)
Dr. Sarvepalli Radhakrishnan (1888-1975)
Dr. Rajendra Prasad (1884-1963)

In [7]:
#5a
from bs4 import BeautifulSoup
import requests
import pandas as pd
url = ('https://www.icc-cricket.com/rankings/mens/team-rankings/odi')
response = requests.get(url)

soup = BeautifulSoup (response.text,"html.parser")
na = soup.find_all('table',class_='table')

team=[]
for i in na:
    for k in i.find_all('span',class_='u-hide-phablet'):
        team.append(k.text.replace('\n',''))
        m=soup.find_all('tr',class_='table-body')
        
        ma=[]
for i in m:
    for j in i.find('td',class_='table-body__cell u-center-text'):
        ma.append(j)
        
       
    z=[]
for i in m:
    for j in i.find_all('td',class_='table-body__cell u-center-text'):
        z.append(j.text.split('\n'))    
        
p=z[1::2]
g=[]
for i in p:
    g.extend(i)


r=[]
for i in m:
    for j in i.find_all('td',class_='table-body__cell u-text-right rating'):
        r.append(j.text)
m=[soup.find('td',class_='rankings-block__banner--matches').text]    
ps=[soup.find('td',class_='rankings-block__banner--points').text]
q=[soup.find('td',class_='rankings-block__banner--rating u-text-right').text.strip()]



mat=m+ma
pt=ps+g
ra=q+r


Men_team=pd.DataFrame({},index=range(1,21))
Men_team["TEAM"]=team
Men_team["MATCHES"]=mat
Men_team["POINTS"]=pt
Men_team["RATING"]=ra


Men_team[0:10]

            TEAM MATCHES POINTS RATING
1        England      27  3,226    119
2    New Zealand      22  2,508    114
3          India      31  3,447    111
4       Pakistan      22  2,354    107
5      Australia      29  3,071    106
6   South Africa      21  2,111    101
7     Bangladesh      30  2,753     92
8      Sri Lanka      29  2,658     92
9    West Indies      41  2,902     71
10   Afghanistan      18  1,238     69

In [30]:
####5. b) Top 10 ODI Batsmen

from urllib.request import urlopen
from bs4 import BeautifulSoup
import pandas as pd
html = urlopen('https://www.icc-cricket.com/rankings/mens/player-rankings/odi/batting')
bs = BeautifulSoup(html, "html.parser")
firstPlayerName = bs.select("div.rankings-block__banner--name-large")[0];
firstPlayerTeam = bs.select("div.rankings-block__banner--nationality")[0];
firstPlayerRating = bs.select("div.rankings-block__banner--rating")[0];

firstPlayer = [firstPlayerName.get_text().strip(),firstPlayerTeam.get_text().strip(),firstPlayerRating.get_text().strip()]

restPlayerName = bs.select("td.rankings-table__name");
restPlayerTeam = bs.select("td.rankings-table__team");
restPlayerRating = bs.select("td.rating");

playerList = []
playerList.append(firstPlayer);


for index in range(0,9):
    name = restPlayerName[index].get_text().strip();
    team = restPlayerTeam[index].get_text().strip();
    rating = restPlayerRating[index].get_text().strip();
    playerList.append([name,team,rating]);
    
df = pd.DataFrame(playerList, columns=["Name","Team", "Rating"])
display(df)

                    Name Team Rating
0             Babar Azam  PAK    890
1  Rassie van der Dussen   SA    789
2        Quinton de Kock   SA    784
3            Imam-ul-Haq  PAK    779
4            Virat Kohli  IND    744
5           Rohit Sharma  IND    740
6         Jonny Bairstow  ENG    732
7           David Warner  AUS    725
8            Ross Taylor   NZ    701
9            Steve Smith  AUS    697

In [16]:
#5c 
page=requests.get('https://www.icc-cricket.com/rankings/mens/player-rankings/odi')
soup=BeautifulSoup(page.content)


name1=soup.find_all('td',class_='table-body__cell name')
name_1=[]
for i in name1:
    for j in i.find('a'):
        name_1.append(j)  
all_name1=name_1[-9:]


team=soup.find_all('td',class_='table-body__cell nationality-logo')
team_1=[]
for i in team:
    for j in i.find_all('span',class_='table-body__logo-text'):
        team_1.append(j.text)        
team_name1=team_1[-9:]



rating=soup.find_all('td',class_='table-body__cell u-text-right rating')
rating_1=[]
for i in rating:
    rating_1.append(i.text)    
rating1=rating_1[-9:]


all_name2=['Trent Boult']
team_name2=['NZ']
rating2=['720']

player_name=all_name2+all_name1
team_name=team_name2+team_name1
rating=rating2+rating1

mens_bowlers=pd.DataFrame({'Player Name':player_name,'Player Team':team_name,'Player Rating':rating},index=range(1,11))

mens_bowlers

         Player Name Player Team Player Rating
1        Trent Boult          NZ           720
2      Mohammad Nabi         AFG           325
3        Rashid Khan         AFG           290
4   Mitchell Santner          NZ           275
5      Sikandar Raza         ZIM           261
6    Zeeshan Maqsood         OMA           238
7       Mehedi Hasan         BAN           238
8       Chris Woakes         ENG           235
9      Glenn Maxwell         AUS           227
10        Imad Wasim         PAK           220

In [17]:
#6a

url1="https://www.icc-cricket.com/rankings/womens/team-rankings/odi"

r=requests.get(url1)

soup=BeautifulSoup(r.content,"html.parser")

na=soup.find_all('table',class_='table')

team=[]
for i in na:
    for k in i.find_all('span',class_='u-hide-phablet'):
        team.append(k.text.replace('\n',''))
        
      
    m=soup.find_all('tr',class_='table-body')


ma=[]
for i in m:
    for j in i.find('td',class_='table-body__cell u-center-text'):
        ma.append(j)
        
      
    z=[]
for i in m:
    for j in i.find_all('td',class_='table-body__cell u-center-text'):
        z.append(j.text.split('\n'))    
        
p=z[1::2]
g=[]
for i in p:
    g.extend(i)

#pars rating
r=[]
for i in m:
    for j in i.find_all('td',class_='table-body__cell u-text-right rating'):
        r.append(j.text)
    
    
    
m=[soup.find('td',class_='rankings-block__banner--matches').text]
ps=[soup.find('td',class_='rankings-block__banner--points').text]
q=[soup.find('td',class_='rankings-block__banner--rating u-text-right').text.strip()]


mat=m+ma
pt=ps+g
ra=q+r


WoMen_team=pd.DataFrame({},index=range(1,12))
WoMen_team["TEAM"]=team
WoMen_team["MATCHES"]=mat
WoMen_team["POINTS"]=pt
WoMen_team["RATING"]=ra


WoMen_team[0:10]

            TEAM MATCHES POINTS RATING
1      Australia      29  4,837    167
2   South Africa      35  4,157    119
3        England      36  4,205    117
4          India      35  3,732    107
5    New Zealand      34  3,342     98
6    West Indies      33  3,014     91
7     Bangladesh      12    930     78
8       Pakistan      30  1,962     65
9        Ireland      11    516     47
10     Sri Lanka      11    495     45

In [18]:
#6b

page=requests.get("https://www.icc-cricket.com/rankings/womens/player-rankings/odi")

soup=BeautifulSoup(page.content)


name1=[soup.find('div',class_='rankings-block__banner--name').text]  
name2=soup.find_all('td',class_='table-body__cell name')  

n2=[]
for i in name2:
    for j in i.find('a'):
        n2.append(j)

name=name1+n2



t=[soup.find('div',class_='rankings-block__banner--nationality')]
t1=t[0].get_text().split()
t1
team1=[t1[0]]   
rating1=[t1[1]] 

tn=soup.find_all('td',class_='table-body__cell nationality-logo')

t2=[]
for i in tn:
    for j in i.find_all('span',class_='table-body__logo-text'):
        t2.append(j.text)
        

team_name=team1+t2


ra=soup.find_all('td',class_='table-body__cell u-text-right rating')


r2=[]
for i in ra:
    r2.append(i.text)
    

rating=rating1+r2


top_10_Batsmen=pd.DataFrame({'Batsmen Name':name[0:10],'Country':team_name[0:10],'Rating':rating[0:10]},index=range(1,11))


top_10_Batsmen[:10]

           Batsmen Name Country Rating
1          Alyssa Healy     AUS    785
2           Beth Mooney     AUS    749
3        Natalie Sciver     ENG    740
4       Laura Wolvaardt      SA    732
5           Meg Lanning     AUS    710
6        Rachael Haynes     AUS    701
7       Smriti Mandhana     IND    698
8     Amy Satterthwaite      NZ    681
9      Harmanpreet Kaur     IND    662
10  Chamari Athapaththu      SL    655

In [19]:
#6c

page=requests.get('https://www.icc-cricket.com/rankings/womens/player-rankings/odi')
soup=BeautifulSoup(page.content)


name1=soup.find_all('td',class_='table-body__cell name')
name_1=[]
for i in name1:
    for j in i.find('a'):
        name_1.append(j)  
all_name1=name_1[-9:]




team=soup.find_all('td',class_='table-body__cell nationality-logo')
team_1=[]
for i in team:
    for j in i.find_all('span',class_='table-body__logo-text'):
        team_1.append(j.text)        
team_name1=team_1[-9:]




rating=soup.find_all('td',class_='table-body__cell u-text-right rating')
rating_1=[]
for i in rating:
    rating_1.append(i.text)    
rating1=rating_1[-9:]



all_name2=['Natalie sciver']
team_name2=['ENG']
rating2=['379']


player_name=all_name2+all_name1
team_name=team_name2+team_name1
rating=rating2+rating1


Women_all_rounder=pd.DataFrame({'Player Name':player_name,'Player Team':team_name,'Player Rating':rating},index=range(1,11))

Women_all_rounder

          Player Name Player Team Player Rating
1      Natalie sciver         ENG           379
2      Natalie Sciver         ENG           372
3      Marizanne Kapp          SA           349
4     Hayley Matthews          WI           339
5         Amelia Kerr          NZ           336
6       Deepti Sharma         IND           271
7    Ashleigh Gardner         AUS           270
8       Jess Jonassen         AUS           246
9      Jhulan Goswami         IND           219
10  Sophie Ecclestone         ENG           217

In [20]:
#7
from bs4 import BeautifulSoup
import requests
import pandas as pd

url = 'https://www.cnbc.com/world/?region=world'

page = requests.get(url)
page

soup = BeautifulSoup(page.content, "html.parser")

headline = soup.find('div', class_='RiverHeadline-headline RiverHeadline-hasThumbnail')
headline.text

headline = []

for i in soup.find_all('div', class_="RiverHeadline-headline RiverHeadline-hasThumbnail"):
    headline.append(i.text)
headline

paper_url = []
for link in soup.findAll("a"):
    if 'href' in link.attrs:
        print(link.attrs['href'])

#MainContent
//www.cnbc.com/world/
/
/markets/
/pre-markets/
/us-markets/
/markets-europe/
/china-markets/
/markets-asia-pacific/
/world-markets/
/currencies/
/cryptocurrency/
/futures-and-commodities/
/bonds/
/funds-and-etfs/
/business/
/economy/
/finance/
/health-and-science/
/media/
/real-estate/
/energy/
/climate/
/transportation/
/industrials/
/retail/
/wealth/
/life/
/small-business/
/investing/
/personal-finance/
/fintech/
/financial-advisors/
/options-action/
/etf-street/
https://buffett.cnbc.com
/earnings/
/trader-talk/
/technology/
/cybersecurity/
/enterprise/
/internet/
/media/
/mobile/
/social-media/
/cnbc-disruptors/
/tech-guide/
/politics/
/white-house/
/policy/
/defense/
/congress/
/equity-opportunity/
/europe-politics/
/china-politics/
/asia-politics/
/world-politics/
/tv/
/live-audio/
/latest-video/
/top-video/
/video-ceo-interviews/
/europe-television/
/asia-business-day/
/podcast/
/digital-original/
/watchlist/
/investingclub/
/investingclub/cramer-trade-alert/
/investingclub/cramers-morning-thoughts/
/investingclub/analysis/
/investingclub/morning-meeting/
/investingclub/charitable-trust/
/pro/
/pro/news/
/pro/
#
#
/make-it/
/?region=usa
/world/
/watchlist/
#
#
/
/markets/
/business/
/investing/
/technology/
/politics/
/tv/
/watchlist/
/investingclub/
/pro/
#
#
#
#
#
https://www.cnbc.com/2022/09/26/european-markets-open-to-close-sterling-slumps-against-the-dollar.html
https://www.cnbc.com/2022/09/25/stock-market-futures-open-to-close-news.html
https://www.cnbc.com/quotes/US10Y
https://www.cnbc.com/2022/09/25/top-wall-street-analysts-say-buy-caterpillar-salesforce.html
https://www.cnbc.com/2022/09/23/google-ceo-pichai-fields-questions-on-cost-cuts-at-all-hands-meeting-.html
https://www.cnbc.com/2022/09/26/this-big-tech-faang-stock-looks-very-attractive-asset-manager-says.html
https://www.cnbc.com/2022/09/24/convertible-sales-fall-in-us-amid-popularity-of-evs-suvs.html
https://www.cnbc.com/2022/09/26/pound-tanking-massive-tax-cuts-and-talk-of-emergency-rate-hikes.html
https://www.cnbc.com/2022/09/26/pound-tanking-massive-tax-cuts-and-talk-of-emergency-rate-hikes.html
https://www.cnbc.com/2022/09/26/sterling-hits-record-low-against-the-dollar-as-other-asia-pacific-currencies-weaken.html
/pro/
https://www.cnbc.com/2022/09/26/best-global-performers-last-week-include-an-energy-stock.html
https://www.cnbc.com/2022/09/26/russia-ukraine-live-updates.html
https://www.cnbc.com/2022/09/26/russia-ukraine-live-updates.html
https://www.cnbc.com/2022/09/26/apple-starts-manufacturing-the-iphone-14-in-india.html
https://www.cnbc.com/2022/09/26/apple-starts-manufacturing-the-iphone-14-in-india.html
https://www.cnbc.com/2022/09/26/walmart-enters-the-metaverse-with-roblox.html
https://www.cnbc.com/2022/09/26/wall-streets-fear-gauge-hits-highest-level-since-june-as-stock-rout-worsens.html
https://www.cnbc.com/2022/09/26/ukraine-russian-stocks-plunge-to-february-invasion-lows.html
/investingclub/
https://www.cnbc.com/2022/09/26/what-the-club-is-watching-monday-bond-yields-rise-dollar-soars-stocks-to-open-lower.html
/pro/
https://www.cnbc.com/2022/09/26/the-signs-traders-are-watching-to-signal-the-stock-market-has-bottomed.html
https://www.cnbc.com/2022/09/26/tiktok-may-face-29-million-uk-fine-for-failing-to-protect-kids-privacy.html
/pro/
https://www.cnbc.com/2022/09/26/goldmans-playbook-on-what-to-buy-and-sell-with-the-us-dollar-surging.html
https://www.cnbc.com/2022/09/26/pound-tanking-massive-tax-cuts-and-talk-of-emergency-rate-hikes.html
/pro/
https://www.cnbc.com/2022/09/26/here-are-mondays-biggest-analyst-calls-planet-fitness-lyft-and-more.html
https://www.cnbc.com/2022/09/26/5-things-to-know-before-the-stock-market-opens-monday-september-26.html
https://www.cnbc.com/2022/09/26/china-extends-ev-tax-break-li-auto-shares-fall-after-delivery-outlook-cut.html
https://www.cnbc.com/2022/09/26/stocks-making-the-biggest-moves-premarket-pge-lyft-las-vegas-sands-more.html
https://www.cnbc.com/2022/09/26/italys-relationship-with-europe-with-fratelli-ditalia-at-the-helm.html
https://www.cnbc.com/2022/09/26/russia-ukraine-live-updates.html
https://www.cnbc.com/2022/09/26/apple-starts-manufacturing-the-iphone-14-in-india.html
https://www.cnbc.com/2022/09/26/2-year-treasury-tops-4point3percent-as-yields-rise-following-fed-rate-hikes.html
https://www.cnbc.com/2022/09/26/the-real-cure-for-inflation-has-gone-ignored-forbes-says.html
https://www.cnbc.com/2022/09/26/brent-crude-slides-below-85-a-barrel-as-dollar-surges.html
https://www.cnbc.com/2022/09/26/amazons-second-prime-day-sale-will-take-place-oct-11-12.html
https://www.cnbc.com/2022/09/26/european-markets-open-to-close-sterling-slumps-against-the-dollar.html
/pro/
https://www.cnbc.com/2022/09/26/best-global-performers-last-week-include-an-energy-stock.html
https://www.cnbc.com/2022/09/26/singapores-temasek-leads-investment-in-chinese-start-up-well-link.html
https://www.cnbc.com/2022/09/26/sterling-hits-record-low-against-the-dollar-as-other-asia-pacific-currencies-weaken.html
https://www.cnbc.com/2022/09/26/how-india-is-trying-to-turn-itself-into-a-semiconductor-powerhouse.html
/pro/
https://www.cnbc.com/2022/09/26/morningstar-picks-high-dividend-global-stocks-and-gives-three-30percent-upside.html
/pro/
https://www.cnbc.com/2022/09/26/this-big-tech-faang-stock-looks-very-attractive-asset-manager-says.html
/pro/
https://www.cnbc.com/2022/09/26/dan-niles-predicts-when-the-sp-500-might-bottom-and-reveals-how-hes-profited.html
https://www.cnbc.com/2022/09/26/asia-markets-stocks-economic-data-currencies-oil.html
https://www.cnbc.com/2022/09/25/stock-market-futures-open-to-close-news.html
https://www.cnbc.com/2022/09/25/italy-elections-giorgia-meloni-and-far-right-brothers-of-italy-top-vote.html
/us-market-movers/
https://www.cnbc.com/2022/09/26/tiktok-may-face-29-million-uk-fine-for-failing-to-protect-kids-privacy.html
https://www.cnbc.com/ryan-browne/
https://www.cnbc.com/2022/09/26/tiktok-may-face-29-million-uk-fine-for-failing-to-protect-kids-privacy.html
https://www.cnbc.com/ryan-browne/
/pro/
https://www.cnbc.com/2022/09/26/dan-niles-predicts-when-the-sp-500-might-bottom-and-reveals-how-hes-profited.html
https://www.cnbc.com/ganesh-rao/
https://www.cnbc.com/2022/09/26/dan-niles-predicts-when-the-sp-500-might-bottom-and-reveals-how-hes-profited.html
https://www.cnbc.com/ganesh-rao/
https://www.cnbc.com/2022/09/26/ukraine-russian-stocks-plunge-to-february-invasion-lows.html
https://www.cnbc.com/elliot-smith/
https://www.cnbc.com/2022/09/26/ukraine-russian-stocks-plunge-to-february-invasion-lows.html
https://www.cnbc.com/elliot-smith/
https://www.cnbc.com/2022/09/25/stock-market-futures-open-to-close-news.html
https://www.cnbc.com/sarah-min/
https://www.cnbc.com/tanaya-macheel/
https://www.cnbc.com/2022/09/25/stock-market-futures-open-to-close-news.html
https://www.cnbc.com/sarah-min/
https://www.cnbc.com/tanaya-macheel/
https://www.cnbc.com/2022/09/26/italys-relationship-with-europe-with-fratelli-ditalia-at-the-helm.html
https://www.cnbc.com/holly-ellyatt/
https://www.cnbc.com/2022/09/26/italys-relationship-with-europe-with-fratelli-ditalia-at-the-helm.html
https://www.cnbc.com/holly-ellyatt/
https://www.cnbc.com/2022/09/26/china-extends-ev-tax-break-li-auto-shares-fall-after-delivery-outlook-cut.html
https://www.cnbc.com/arjun-kharpal/
https://www.cnbc.com/2022/09/26/china-extends-ev-tax-break-li-auto-shares-fall-after-delivery-outlook-cut.html
https://www.cnbc.com/arjun-kharpal/
https://www.cnbc.com/2022/09/26/brent-crude-slides-below-85-a-barrel-as-dollar-surges.html
https://www.cnbc.com/hannah-ward-glenton/
https://www.cnbc.com/2022/09/26/brent-crude-slides-below-85-a-barrel-as-dollar-surges.html
https://www.cnbc.com/hannah-ward-glenton/
https://www.cnbc.com/2022/09/26/how-india-is-trying-to-turn-itself-into-a-semiconductor-powerhouse.html
https://www.cnbc.com/2022/09/26/how-india-is-trying-to-turn-itself-into-a-semiconductor-powerhouse.html
https://www.cnbc.com/2022/09/25/avatar-re-release-shows-franchises-overseas-strength.html
https://www.cnbc.com/2022/09/25/avatar-re-release-shows-franchises-overseas-strength.html
https://www.cnbc.com/2022/09/25/italy-elections-giorgia-meloni-and-far-right-brothers-of-italy-top-vote.html
https://www.cnbc.com/matt-clinch/
https://www.cnbc.com/2022/09/25/italy-elections-giorgia-meloni-and-far-right-brothers-of-italy-top-vote.html
https://www.cnbc.com/matt-clinch/
/pro/
https://www.cnbc.com/2022/09/26/morningstar-picks-high-dividend-global-stocks-and-gives-three-30percent-upside.html
https://www.cnbc.com/ganesh-rao/
https://www.cnbc.com/2022/09/26/morningstar-picks-high-dividend-global-stocks-and-gives-three-30percent-upside.html
https://www.cnbc.com/ganesh-rao/
https://www.cnbc.com/2022/09/26/the-real-cure-for-inflation-has-gone-ignored-forbes-says.html
https://www.cnbc.com/su-lin-tan/
https://www.cnbc.com/2022/09/26/the-real-cure-for-inflation-has-gone-ignored-forbes-says.html
https://www.cnbc.com/su-lin-tan/
https://www.cnbc.com/2022/09/26/asia-markets-stocks-economic-data-currencies-oil.html
https://www.cnbc.com/abigail-ng/
https://www.cnbc.com/2022/09/26/asia-markets-stocks-economic-data-currencies-oil.html
https://www.cnbc.com/abigail-ng/
https://www.cnbc.com/2022/09/24/us-sending-dangerous-signals-on-taiwan-china-tells-blinken.html
https://www.cnbc.com/2022/09/24/us-sending-dangerous-signals-on-taiwan-china-tells-blinken.html
https://www.cnbc.com/2022/09/26/13-dead-21-wounded-in-school-shooting-in-russia.html
https://www.cnbc.com/2022/09/26/13-dead-21-wounded-in-school-shooting-in-russia.html
https://www.cnbc.com/2022/09/26/energy-inflation-crises-risk-pushing-big-economies-into-recession-oecd.html
https://www.cnbc.com/2022/09/26/energy-inflation-crises-risk-pushing-big-economies-into-recession-oecd.html
https://www.cnbc.com/2022/09/26/amazons-second-prime-day-sale-will-take-place-oct-11-12.html
https://www.cnbc.com/annie-palmer/
https://www.cnbc.com/2022/09/26/amazons-second-prime-day-sale-will-take-place-oct-11-12.html
https://www.cnbc.com/annie-palmer/
https://www.cnbc.com/2022/09/26/singapores-temasek-leads-investment-in-chinese-start-up-well-link.html
https://www.cnbc.com/evelyn-cheng/
https://www.cnbc.com/2022/09/26/singapores-temasek-leads-investment-in-chinese-start-up-well-link.html
https://www.cnbc.com/evelyn-cheng/
/pro/
https://www.cnbc.com/2022/09/26/this-big-tech-faang-stock-looks-very-attractive-asset-manager-says.html
https://www.cnbc.com/weizhen-tan/
https://www.cnbc.com/2022/09/26/this-big-tech-faang-stock-looks-very-attractive-asset-manager-says.html
https://www.cnbc.com/weizhen-tan/
https://www.cnbc.com/2022/09/25/zelenskyy-on-putins-threat-of-nuclear-weapons-i-dont-think-hes-bluffing.html
https://www.cnbc.com/ashley-capoot/
https://www.cnbc.com/jack-stebbins/
https://www.cnbc.com/2022/09/25/zelenskyy-on-putins-threat-of-nuclear-weapons-i-dont-think-hes-bluffing.html
https://www.cnbc.com/ashley-capoot/
https://www.cnbc.com/jack-stebbins/
//www.cnbc.com/us-market-movers/
/us-market-movers/
/stocks/
https://www.cnbc.com/2022/09/26/wall-streets-fear-gauge-hits-highest-level-since-june-as-stock-rout-worsens.html
https://www.cnbc.com/yun-li/
https://www.cnbc.com/2022/09/26/stocks-making-the-biggest-moves-premarket-pge-lyft-las-vegas-sands-more.html
https://www.cnbc.com/yun-li/
https://www.cnbc.com/2022/09/26/the-signs-traders-are-watching-to-signal-the-stock-market-has-bottomed.html
/pro/
https://www.cnbc.com/bob-pisani/
https://www.cnbc.com/2022/09/25/stock-market-futures-open-to-close-news.html
https://www.cnbc.com/sarah-min/
https://www.cnbc.com/tanaya-macheel/
//www.cnbc.com/live-tv/
//www.cnbc.com/latest-video/
https://www.cnbc.com/video/2022/09/22/how-these-startups-are-fixing-water-waste-on-farms.html
https://www.cnbc.com/video/2022/09/20/why-layoffs-may-be-on-the-horizon-in-the-us.html
https://www.cnbc.com/video/2022/09/23/the-fed-will-have-to-take-the-terminal-funds-rate-higher-in-23-says-former-kc-fed-president.html
https://www.cnbc.com/special-reports/
https://www.cnbc.com/2022/09/26/the-real-cure-for-inflation-has-gone-ignored-forbes-says.html
https://www.cnbc.com/2022/09/26/russia-ukraine-live-updates.html
https://www.cnbc.com/2022/09/26/amazons-second-prime-day-sale-will-take-place-oct-11-12.html
https://www.cnbc.com/2022/09/26/5-things-to-know-before-the-stock-market-opens-monday-september-26.html
https://www.cnbc.com/2022/09/25/stock-market-futures-open-to-close-news.html
https://www.cnbc.com/pro/news/
https://www.cnbc.com/2022/09/26/the-signs-traders-are-watching-to-signal-the-stock-market-has-bottomed.html
https://www.cnbc.com/2022/09/26/the-signs-traders-are-watching-to-signal-the-stock-market-has-bottomed.html
/pro/
https://www.cnbc.com/bob-pisani/
https://www.cnbc.com/2022/09/26/wall-streets-fear-gauge-hits-highest-level-since-june-as-stock-rout-worsens.html
https://www.cnbc.com/2022/09/26/wall-streets-fear-gauge-hits-highest-level-since-june-as-stock-rout-worsens.html
https://www.cnbc.com/yun-li/
https://www.cnbc.com/2022/09/26/goldmans-playbook-on-what-to-buy-and-sell-with-the-us-dollar-surging.html
https://www.cnbc.com/2022/09/26/goldmans-playbook-on-what-to-buy-and-sell-with-the-us-dollar-surging.html
/pro/
https://www.cnbc.com/john-melloy/
https://www.cnbc.com/2022/09/26/here-are-mondays-biggest-analyst-calls-planet-fitness-lyft-and-more.html
https://www.cnbc.com/2022/09/26/here-are-mondays-biggest-analyst-calls-planet-fitness-lyft-and-more.html
/pro/
https://www.cnbc.com/yun-li/
https://www.cnbc.com/2022/09/26/best-global-performers-last-week-include-an-energy-stock.html
https://www.cnbc.com/2022/09/26/best-global-performers-last-week-include-an-energy-stock.html
/pro/
https://www.cnbc.com/weizhen-tan/
https://www.cnbc.com/sustainable-future/
https://www.cnbc.com/2022/09/21/big-businesses-trumpet-esg-credentials-scrutiny-is-on-the-rise.html
https://www.cnbc.com/2022/09/21/big-businesses-trumpet-esg-credentials-scrutiny-is-on-the-rise.html
https://www.cnbc.com/anmar-frangoul-profile--cnbc/
https://www.cnbc.com/2022/09/20/uns-guterres-says-polluters-must-pay-calls-for-tax-on-fossil-fuels.html
https://www.cnbc.com/2022/09/20/uns-guterres-says-polluters-must-pay-calls-for-tax-on-fossil-fuels.html
https://www.cnbc.com/anmar-frangoul-profile--cnbc/
https://www.cnbc.com/2022/09/07/uks-new-energy-chief-says-fracking-interesting-we-need-fossil-fuels.html
https://www.cnbc.com/2022/09/07/uks-new-energy-chief-says-fracking-interesting-we-need-fossil-fuels.html
https://www.cnbc.com/anmar-frangoul-profile--cnbc/
https://www.cnbc.com/video/2022/09/08/undps-human-development-report-uncertain-times-unsettled-lives.html
https://www.cnbc.com/video/2022/09/08/undps-human-development-report-uncertain-times-unsettled-lives.html
https://www.cnbc.com/tania-bryer/
https://www.cnbc.com/2022/09/01/huge-offshore-wind-farm-hornsea-2-is-fully-operational-orsted-says.html
https://www.cnbc.com/2022/09/01/huge-offshore-wind-farm-hornsea-2-is-fully-operational-orsted-says.html
https://www.cnbc.com/anmar-frangoul-profile--cnbc/
https://www.cnbc.com/coronavirus/
https://www.cnbc.com/2022/09/23/moderna-asks-fda-to-authorize-omicron-covid-boosters-for-children-as-young-as-6-years-old.html
https://www.cnbc.com/2022/09/23/moderna-asks-fda-to-authorize-omicron-covid-boosters-for-children-as-young-as-6-years-old.html
https://www.cnbc.com/spencer-kimball/
https://www.cnbc.com/2022/09/22/who-warns-ability-to-identify-new-covid-variants-is-diminishing-as-testing-declines-.html
https://www.cnbc.com/2022/09/22/who-warns-ability-to-identify-new-covid-variants-is-diminishing-as-testing-declines-.html
https://www.cnbc.com/spencer-kimball/
https://www.cnbc.com/2022/09/21/watch-ukrainian-president-zelenskyy-addresses-un-general-assembly.html
https://www.cnbc.com/2022/09/21/watch-ukrainian-president-zelenskyy-addresses-un-general-assembly.html
https://www.cnbc.com/2022/09/21/what-another-major-rate-hike-by-the-federal-reserve-means-to-you.html
https://www.cnbc.com/2022/09/21/what-another-major-rate-hike-by-the-federal-reserve-means-to-you.html
https://www.cnbc.com/jessica-dickler/
https://www.cnbc.com/2022/09/20/layoffs-loom-on-the-horizon-some-economists-say.html
https://www.cnbc.com/2022/09/20/layoffs-loom-on-the-horizon-some-economists-say.html
https://www.cnbc.com/andrea-miller/
https://www.cnbc.com/cnbc-travel/
https://www.cnbc.com/2022/09/22/what-are-the-most-common-crimes-in-hotels-not-theft-say-uk-police-.html
https://www.cnbc.com/2022/09/22/what-are-the-most-common-crimes-in-hotels-not-theft-say-uk-police-.html
https://www.cnbc.com/jenni-reid/
https://www.cnbc.com/2022/09/19/how-much-does-it-cost-to-visit-bhutan-200-a-day-plus-travel-costs-.html
https://www.cnbc.com/2022/09/19/how-much-does-it-cost-to-visit-bhutan-200-a-day-plus-travel-costs-.html
https://www.cnbc.com/monica-pitrelli/
https://www.cnbc.com/2022/09/16/woman-ochre-de-koonings-painting-from-theft-to-its-return-home.html
https://www.cnbc.com/2022/09/16/woman-ochre-de-koonings-painting-from-theft-to-its-return-home.html
https://www.cnbc.com/monica-pitrelli/
https://www.cnbc.com/2022/09/12/best-hotels-for-business-travelers-in-asia-pacific.html
https://www.cnbc.com/2022/09/12/best-hotels-for-business-travelers-in-asia-pacific.html
https://www.cnbc.com/monica-pitrelli/
https://www.cnbc.com/2022/09/09/where-russians-go-on-vacation-since-the-ukraine-war-started.html
https://www.cnbc.com/2022/09/09/where-russians-go-on-vacation-since-the-ukraine-war-started.html
https://www.cnbc.com/lee-ying-shan/
https://www.cnbc.com/make-it/
https://www.cnbc.com/2022/09/25/the-3-biggest-signs-of-passive-aggressive-and-childish-behavior-harvard-body-language-expert.html
https://www.cnbc.com/2022/09/25/the-3-biggest-signs-of-passive-aggressive-and-childish-behavior-harvard-body-language-expert.html
https://www.cnbc.com/erica-dhawan/
https://www.cnbc.com/2022/09/25/this-millennial-got-fired-and-re-hired-at-the-same-company-in-24-hours.html
https://www.cnbc.com/2022/09/25/this-millennial-got-fired-and-re-hired-at-the-same-company-in-24-hours.html
https://www.cnbc.com/morgan-smith/
https://www.cnbc.com/2022/09/25/the-6-best-business-books-of-the-year-according-to-financial-times.html
https://www.cnbc.com/2022/09/25/the-6-best-business-books-of-the-year-according-to-financial-times.html
https://www.cnbc.com/tom-huddleston-jr/
https://www.cnbc.com/2022/09/25/mark-cuban-says-hes-too-competitive-to-retire-at-age-64.html
https://www.cnbc.com/2022/09/25/mark-cuban-says-hes-too-competitive-to-retire-at-age-64.html
https://www.cnbc.com/megan-sauer/
https://www.cnbc.com/2022/09/24/three-rules-for-a-successful-open-relationship.html
https://www.cnbc.com/2022/09/24/three-rules-for-a-successful-open-relationship.html
https://www.cnbc.com/aditi-shrikant-bio/
https://www.cnbc.com/investing-in-supertrends/
https://www.cnbc.com/2022/08/18/web3-is-in-chaos-metaverses-in-walled-gardens-randi-zuckerberg.html
https://www.cnbc.com/2022/08/18/web3-is-in-chaos-metaverses-in-walled-gardens-randi-zuckerberg.html
https://www.cnbc.com/goh-chiew-tong/
https://www.cnbc.com/2022/08/17/japan-support-for-nuclear-restart-is-highest-since-fukushima-disaster.html
https://www.cnbc.com/2022/08/17/japan-support-for-nuclear-restart-is-highest-since-fukushima-disaster.html
https://www.cnbc.com/lee-ying-shan/
https://www.cnbc.com/2022/08/10/india-australia-singapore-firms-jobs-are-in-these-sectors-linkedin.html
https://www.cnbc.com/2022/08/10/india-australia-singapore-firms-jobs-are-in-these-sectors-linkedin.html
https://www.cnbc.com/charmaine-jacob/
https://www.cnbc.com/2022/08/08/baidus-robotaxis-dont-need-any-human-staff-in-these-parts-of-china.html
https://www.cnbc.com/2022/08/08/baidus-robotaxis-dont-need-any-human-staff-in-these-parts-of-china.html
https://www.cnbc.com/evelyn-cheng/
https://www.cnbc.com/2021/07/26/action-on-climate-change-can-boost-global-economy-economist-says.html
https://www.cnbc.com/2021/07/26/action-on-climate-change-can-boost-global-economy-economist-says.html
//www.cnbc.com

In [21]:
#8
from bs4 import BeautifulSoup
import requests
import pandas as pd
url='https://www.journals.elsevier.com/artificial-intelligence/most-downloaded-articles'
page = requests.get(url)

soup = BeautifulSoup(page.text,'lxml')

paper_title=soup.find('a', class_="sc-5smygv-0 nrDZj")
paper_title

author = soup.find('span', class_='sc-1w3fpd7-0 pgLAT')
author.text

published_date = soup.find('span', class_='sc-1thf9ly-2 bKddwo')
published_date.text

paper_url = []
for link in soup.findAll("a"):
    if 'href' in link.attrs:
        print(link.attrs['href'])
paper_url

#skip-to-content-anchor
http://www.elsevier.com
https://account.elsevier.com/auth
https://elsevier.com/about
https://www.elsevier.com/connect
https://www.elsevier.com/about/careers
https://elsevier.com/about
https://www.elsevier.com/connect
https://www.elsevier.com/about/careers
https://www.elsevier.com/rd-solutions
https://www.elsevier.com/clinical-solutions
https://www.elsevier.com/research-platforms
https://www.elsevier.com/research-intelligence
https://www.elsevier.com/education
https://www.elsevier.com/solutions
https://www.elsevier.com/rd-solutions
https://www.elsevier.com/clinical-solutions
https://www.elsevier.com/research-platforms
https://www.elsevier.com/research-intelligence
https://www.elsevier.com/education
https://www.elsevier.com/solutions
https://www.elsevier.com/authors
https://www.elsevier.com/editors
https://www.elsevier.com/reviewers
https://www.elsevier.com/librarians
https://www.elsevier.com/strategic-partners
https://www.elsevier.com/open-access
https://www.elsevier.com/societies
https://www.elsevier.com/authors
https://www.elsevier.com/editors
https://www.elsevier.com/reviewers
https://www.elsevier.com/librarians
https://www.elsevier.com/strategic-partners
https://www.elsevier.com/open-access
https://www.elsevier.com/societies
https://www.elsevier.com/books-and-journals
https://webshop.elsevier.com/?utm_source=ecom&utm_medium=top&utm_campaign=webshop
https://www.elsevier.com/books-and-journals
https://webshop.elsevier.com/?utm_source=ecom&utm_medium=top&utm_campaign=webshop
https://global-checkout.elsevier.com
https://account.elsevier.com/auth
https://www.sciencedirect.com/science/journal/00043702
https://www.editorialmanager.com/artint/default.aspx
https://www.elsevier.com/
https://www.elsevier.com/search-results?labels=journals
/artificial-intelligence
/artificial-intelligence/most-downloaded-articles
https://www.sciencedirect.com/science/journal/00043702
https://www.editorialmanager.com/artint/default.aspx
https://www.sciencedirect.com/science/journal/00043702
https://www.elsevier.com/journals/artificial-intelligence/0004-3702/guide-for-authors
https://www.editorialmanager.com/artint/default.aspx
https://authors.elsevier.com/tracking/landingpage/selection.do
https://www.elsevier.com/journals/artificial-intelligence/0004-3702/subscribe?subscriptiontype=institutional
https://www.sciencedirect.com/science/article/pii/S0004370221000862
https://www.sciencedirect.com/science/article/pii/S0004370221000722
https://www.sciencedirect.com/science/article/pii/S0004370215000910
https://www.sciencedirect.com/science/article/pii/S0004370298000551
https://www.sciencedirect.com/science/article/pii/S0004370216300790
https://www.sciencedirect.com/science/article/pii/S0004370218305988
https://www.sciencedirect.com/science/article/pii/S0004370220301855
https://www.sciencedirect.com/science/article/pii/S0004370214001386
https://www.sciencedirect.com/science/article/pii/S0004370299000521
https://www.sciencedirect.com/science/article/pii/S0004370219300116
https://www.sciencedirect.com/science/article/pii/S0004370220301533
https://www.sciencedirect.com/science/article/pii/S0004370207000793
https://www.sciencedirect.com/science/article/pii/S0004370216300285
https://www.sciencedirect.com/science/article/pii/S0004370220301958
https://www.sciencedirect.com/science/article/pii/S0004370297000635
https://www.sciencedirect.com/science/article/pii/S0004370221000515
https://www.sciencedirect.com/science/article/pii/S0004370221000539
https://www.sciencedirect.com/science/article/pii/S0004370221000096
https://www.sciencedirect.com/science/article/pii/S0004370216300868
https://www.sciencedirect.com/science/article/pii/S0004370221000588
https://www.sciencedirect.com/science/article/pii/S0004370221000102
https://www.sciencedirect.com/science/article/pii/S0004370213001082
https://www.sciencedirect.com/science/article/pii/S000437029700043X
https://www.sciencedirect.com/science/article/pii/S0004370221000734
https://www.sciencedirect.com/science/article/pii/S0004370209001398
https://www.sciencedirect.com/science/journal/00043702
https://www.sciencedirect.com/user/alerts
https://www.sciencedirect.com/user/register?utm_campaign=sd_recommender_ELSJLS&utm_channel=elseco&dgcid=sd_recommender_ELSJLS
http://www.elsevier.com/authors/home
https://www.editorialmanager.com/artint/default.aspx
https://www.editorialmanager.com/artint/default.aspx
https://researcheracademy.elsevier.com
https://www.elsevier.com/about/policies/copyright/permissions
https://webshop.elsevier.com
https://service.elsevier.com/app/home/supporthub/publishing/#authors
https://authors.elsevier.com/tracking/landingpage/selection.do
https://www.elsevier.com/librarians
https://www.elsevier.com/journals/artificial-intelligence/0004-3702/subscribe?subscriptiontype=institutional
http://www.elsevier.com/editors
http://www.elsevier.com/editors/perk
https://www.elsevier.com/editors/guest-editors
https://service.elsevier.com/app/home/supporthub/publishing/#editors
http://www.elsevier.com/reviewers
https://www.elsevier.com/reviewers/how-to-review
https://www.editorialmanager.com/artint/default.aspx
https://www.elsevier.com/reviewers/becoming-a-reviewer-how-and-why#recognizing
https://service.elsevier.com/app/home/supporthub/publishing/#reviewers
https://www.elsevier.com
//www.elsevier.com/legal/elsevier-website-terms-and-conditions
//www.elsevier.com/legal/privacy-policy
//www.elsevier.com/legal/cookienotice
//www.elsevier.com/sitemap
https://www.relx.com/

[]

In [22]:
#8
paper_titles = []

for i in soup.find_all('a', class_="sc-5smygv-0 nrDZj"):
    paper_titles.append(i.text)
paper_titles

['Reward is enough',
 'Making sense of raw input',
 'Law and logic: A review from an argumentation perspective',
 'Creativity and artificial intelligence',
 'Artificial cognition for social human–robot interaction: An implementation',
 'Explanation in artificial intelligence: Insights from the social sciences',
 'Making sense of sensory input',
 'Conflict-based search for optimal multi-agent pathfinding',
 'Between MDPs and semi-MDPs: A framework for temporal abstraction in reinforcement learning',
 'The Hanabi challenge: A new frontier for AI research',
 'Evaluating XAI: A comparison of rule-based and example-based explanations',
 'Argumentation in artificial intelligence',
 'Algorithms for computing strategies in two-player simultaneous move games',
 'Multiple object tracking: A literature review',
 'Selection of relevant features and examples in machine learning',
 'A survey of inverse reinforcement learning: Challenges, methods and progress',
 'Explaining individual predictions when features are dependent: More accurate approximations to Shapley values',
 'A review of possible effects of cognitive biases on interpretation of rule-based machine learning models',
 'Integrating social power into the decision-making of cognitive agents',
 "“That's (not) the output I expected!” On the role of end user expectations in creating explanations of AI systems",
 'Explaining black-box classifiers using post-hoc explanations-by-example: The effect of explanations and error-rates in XAI user studies',
 'Algorithm runtime prediction: Methods & evaluation',
 'Wrappers for feature subset selection',
 'Commonsense visual sensemaking for autonomous driving – On generalised neurosymbolic online abduction integrating vision and semantics',
 'Quantum computation, quantum theory and AI']

In [23]:
#8
author = []

for i in soup.find_all('span', class_='sc-1w3fpd7-0 pgLAT'):
    author.append(i.text)
author

['Silver, David, Singh, Satinder, Precup, Doina, Sutton, Richard S. ',
 'Evans, Richard, Bošnjak, Matko and 5 more',
 'Prakken, Henry, Sartor, Giovanni ',
 'Boden, Margaret A. ',
 'Lemaignan, Séverin, Warnier, Mathieu and 3 more',
 'Miller, Tim ',
 'Evans, Richard, Hernández-Orallo, José and 3 more',
 'Sharon, Guni, Stern, Roni, Felner, Ariel, Sturtevant, Nathan R. ',
 'Sutton, Richard S., Precup, Doina, Singh, Satinder ',
 'Bard, Nolan, Foerster, Jakob N. and 13 more',
 'van der Waa, Jasper, Nieuwburg, Elisabeth, Cremers, Anita, Neerincx, Mark ',
 'Bench-Capon, T.J.M., Dunne, Paul E. ',
 'Bošanský, Branislav, Lisý, Viliam and 3 more',
 'Luo, Wenhan, Xing, Junliang and 4 more',
 'Blum, Avrim L., Langley, Pat ',
 'Arora, Saurabh, Doshi, Prashant ',
 'Aas, Kjersti, Jullum, Martin, Løland, Anders ',
 'Kliegr, Tomáš, Bahník, Štěpán, Fürnkranz, Johannes ',
 'Pereira, Gonçalo, Prada, Rui, Santos, Pedro A. ',
 'Riveiro, Maria, Thill, Serge ',
 'Kenny, Eoin M., Ford, Courtney, Quinn, Molly, Keane, Mark T. ',
 'Hutter, Frank, Xu, Lin, Hoos, Holger H., Leyton-Brown, Kevin ',
 'Kohavi, Ron, John, George H. ',
 'Suchan, Jakob, Bhatt, Mehul, Varadarajan, Srikrishna ',
 'Ying, Mingsheng ']

In [24]:
#8
published_date = []

for i in soup.find_all('span', class_='sc-1thf9ly-2 bKddwo'):
    published_date.append(i.text)
published_date

['October 2021',
 'October 2021',
 'October 2015',
 'August 1998',
 'June 2017',
 'February 2019',
 'April 2021',
 'February 2015',
 'August 1999',
 'March 2020',
 'February 2021',
 'October 2007',
 'August 2016',
 'April 2021',
 'December 1997',
 'August 2021',
 'September 2021',
 'June 2021',
 'December 2016',
 'September 2021',
 'May 2021',
 'January 2014',
 'December 1997',
 'October 2021',
 'February 2010']

In [25]:
#9
from bs4 import BeautifulSoup
import requests
import pandas as pd
page = requests.get('https://www.dineout.co.in/delhi-restaurants/buffet-special')
page
soup = BeautifulSoup(page.content)
soup
names = []

for i in soup.find_all('div',class_="restnt-info cursor"):
    names.append(i.text)
    
names
locations = []

for i in soup.find_all('div',class_="restnt-loc ellipsis"):
    locations.append(i.text)
    
locations
price = []

for i in soup.find_all('span',class_="double-line-ellipsis"):
    price.append(i.text)
    
price
images = []

for i in soup.find_all("img",class_="no-img"):
    images.append(i['data-src'])
    
images
import pandas as pd
df = pd.DataFrame({'Names':names,'Locations':locations,'Price and Cuisine':price,'Images_url':images})
df

,Names,Locations,Price and Cuisine,Images_url
0,"Castle BarbequeConnaught Place, Central Delhi","Connaught Place, Central Delhi","₹ 2,000 for 2 (approx) | Chinese, North Indian",https://im1.dineout.co.in/images/uploads/resta...
1,"Jungle Jamboree3CS Mall,Lajpat Nagar - 3, Sout...","3CS Mall,Lajpat Nagar - 3, South Delhi","₹ 1,680 for 2 (approx) | North Indian, Asian, ...",https://im1.dineout.co.in/images/uploads/resta...
2,"Castle BarbequePacific Mall,Tagore Garden, Wes...","Pacific Mall,Tagore Garden, West Delhi","₹ 2,000 for 2 (approx) | Chinese, North Indian",https://im1.dineout.co.in/images/uploads/resta...
3,"Cafe KnoshThe Leela Ambience Convention Hotel,...","The Leela Ambience Convention Hotel,Shahdara, ...","₹ 3,000 for 2 (approx) | Italian, Continental",https://im1.dineout.co.in/images/uploads/resta...
4,"The Barbeque CompanyGardens Galleria,Sector 38...","Gardens Galleria,Sector 38A, Noida","₹ 1,700 for 2 (approx) | North Indian, Chinese",https://im1.dineout.co.in/images/uploads/resta...
5,"India GrillHilton Garden Inn,Saket, South Delhi","Hilton Garden Inn,Saket, South Delhi","₹ 2,400 for 2 (approx) | North Indian, Italian",https://im1.dineout.co.in/images/uploads/resta...
6,"Delhi BarbequeTaurus Sarovar Portico,Mahipalpu...","Taurus Sarovar Portico,Mahipalpur, South Delhi","₹ 1,800 for 2 (approx) | North Indian",https://im1.dineout.co.in/images/uploads/resta...
7,The Monarch - Bar Be Que VillageIndirapuram Ha...,"Indirapuram Habitat Centre,Indirapuram, Ghaziabad","₹ 1,900 for 2 (approx) | North Indian",https://im1.dineout.co.in/images/uploads/resta...
8,"Indian Grill RoomSuncity Business Tower,Golf C...","Suncity Business Tower,Golf Course Road, Gurgaon","₹ 2,200 for 2 (approx) | North Indian, Mughlai",https://im1.dineout.co.in/images/uploads/resta...

In [26]:
#10
from bs4 import BeautifulSoup
import requests
import pandas as pd
import re

url = 'https://scholar.google.com/citations?view_op=top_venues&hl=en'
page = requests.get(url)
page

soup = BeautifulSoup(page.content, "html.parser")

first_title=soup.find('th', class_="gsc_mvt_t")
first_title.text
'Publication'

index = soup.find('th', class_='gsc_mvt_n')
index.text


median = soup.find('span', class_="gs_ibl gsc_mp_anchor")
median.text

publication = []

for i in soup.find_all('td', class_="gsc_mvt_t"):
    publication.append(i.text)
publication

['Nature',
 'The New England Journal of Medicine',
 'Science',
 'IEEE/CVF Conference on Computer Vision and Pattern Recognition',
 'The Lancet',
 'Advanced Materials',
 'Nature Communications',
 'Cell',
 'International Conference on Learning Representations',
 'Neural Information Processing Systems',
 'JAMA',
 'Chemical Reviews',
 'Proceedings of the National Academy of Sciences',
 'Angewandte Chemie',
 'Chemical Society Reviews',
 'Journal of the American Chemical Society',
 'IEEE/CVF International Conference on Computer Vision',
 'Nucleic Acids Research',
 'International Conference on Machine Learning',
 'Nature Medicine',
 'Renewable and Sustainable Energy Reviews',
 'Science of The Total Environment',
 'Advanced Energy Materials',
 'Journal of Clinical Oncology',
 'ACS Nano',
 'Journal of Cleaner Production',
 'Advanced Functional Materials',
 'Physical Review Letters',
 'Scientific Reports',
 'The Lancet Oncology',
 'Energy & Environmental Science',
 'IEEE Access',
 'PLoS ONE',
 'Science Advances',
 'Journal of the American College of Cardiology',
 'Applied Catalysis B: Environmental',
 'Nature Genetics',
 'BMJ',
 'Circulation',
 'European Conference on Computer Vision',
 'International Journal of Molecular Sciences',
 'Nature Materials',
 'Chemical engineering journal',
 'AAAI Conference on Artificial Intelligence',
 'Journal of Materials Chemistry A',
 'ACS Applied Materials & Interfaces',
 'Nature Biotechnology',
 'The Lancet Infectious Diseases',
 'Frontiers in Immunology',
 'Applied Energy',
 'Nano Energy',
 'Nature Energy',
 'Meeting of the Association for Computational Linguistics (ACL)',
 'The Astrophysical Journal',
 'Gastroenterology',
 'Nature Methods',
 'IEEE Transactions on Pattern Analysis and Machine Intelligence',
 'Cochrane Database of Systematic Reviews',
 'Blood',
 'Neuron',
 'Nano Letters',
 'Morbidity and Mortality Weekly Report',
 'European Heart Journal',
 'Nature Nanotechnology',
 'ACS Catalysis',
 'Nature Neuroscience',
 'American Economic Review',
 'Journal of High Energy Physics',
 'IEEE Communications Surveys & Tutorials',
 'Annals of Oncology',
 'Nutrients',
 'Accounts of Chemical Research',
 'Immunity',
 'Environmental Science & Technology',
 'Nature Reviews. Molecular Cell Biology',
 'Gut',
 'Physical Review D',
 'ACS Energy Letters',
 'Monthly Notices of the Royal Astronomical Society',
 'Conference on Empirical Methods in Natural Language Processing (EMNLP)',
 'Clinical Infectious Diseases',
 'Cell Metabolism',
 'Nature Reviews Immunology',
 'Joule',
 'Nature Photonics',
 'International Journal of Environmental Research and Public Health',
 'Environmental Pollution',
 'Computers in Human Behavior',
 'Frontiers in Microbiology',
 'Nature Physics',
 'Small',
 'Cell Reports',
 'Molecular Cell',
 'Clinical Cancer Research',
 'Bioresource Technology',
 'Journal of Business Research',
 'Molecular Cancer',
 'Sensors',
 'Nature Climate Change',
 'IEEE Internet of Things Journal']

In [27]:
index = []

for i in soup.find_all('td', class_="gsc_mvt_n"):
    index.append(i.text)

index

['444',
 '667',
 '432',
 '780',
 '401',
 '614',
 '389',
 '627',
 '354',
 '635',
 '312',
 '418',
 '307',
 '428',
 '300',
 '505',
 '286',
 '533',
 '278',
 '436',
 '267',
 '425',
 '265',
 '444',
 '256',
 '364',
 '245',
 '332',
 '244',
 '386',
 '242',
 '344',
 '239',
 '415',
 '238',
 '550',
 '237',
 '421',
 '235',
 '389',
 '227',
 '324',
 '225',
 '311',
 '220',
 '300',
 '213',
 '315',
 '211',
 '277',
 '211',
 '273',
 '210',
 '280',
 '207',
 '294',
 '206',
 '274',
 '202',
 '329',
 '202',
 '290',
 '200',
 '303',
 '198',
 '278',
 '197',
 '294',
 '195',
 '276',
 '192',
 '246',
 '191',
 '297',
 '190',
 '307',
 '189',
 '301',
 '186',
 '321',
 '183',
 '253',
 '181',
 '265',
 '181',
 '224',
 '180',
 '296',
 '178',
 '220',
 '177',
 '223',
 '175',
 '315',
 '173',
 '296',
 '173',
 '228',
 '173',
 '217',
 '172',
 '232',
 '170',
 '314',
 '169',
 '304',
 '167',
 '234',
 '166',
 '254',
 '165',
 '296',
 '165',
 '293',
 '165',
 '243',
 '165',
 '229',
 '164',
 '231',
 '164',
 '207',
 '163',
 '302',
 '163',
 '265',
 '163',
 '264',
 '163',
 '220',
 '162',
 '248',
 '160',
 '263',
 '160',
 '220',
 '159',
 '304',
 '159',
 '243',
 '159',
 '214',
 '159',
 '211',
 '158',
 '242',
 '158',
 '214',
 '155',
 '340',
 '155',
 '235',
 '155',
 '217',
 '155',
 '212',
 '155',
 '194',
 '154',
 '249',
 '153',
 '278',
 '153',
 '211',
 '152',
 '292',
 '152',
 '233',
 '152',
 '228',
 '152',
 '225',
 '152',
 '222',
 '152',
 '214',
 '151',
 '225',
 '151',
 '222',
 '150',
 '196',
 '149',
 '205',
 '149',
 '202',
 '146',
 '201',
 '146',
 '190',
 '145',
 '233',
 '145',
 '209',
 '145',
 '201',
 '144',
 '228',
 '144',
 '212']